### ISSUE TITLE
Application crashes when initiating AppRater

### ISSUE THREAD

**Issue by ido567** [codechimp-org/AppRater#42]
When I initiate the plugin in my application class with this code:
````java
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        // Init AndroidRecord
        ActiveAndroid.initialize(this);

        // Init app rater, and enable version check (which will re-enable the prompt count if
        // a new version is installed)
        AppRater.app_launched(this);
        AppRater.setVersionCodeCheckEnabled(true);
   }
}
````

I'm getting this fatal error:
````java
01-09 17:56:16.482  20542-20542/com.soccertimer.android.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.soccertimer.android.debug, PID: 20542
    java.lang.RuntimeException: Unable to create application com.soccertimer.android.utils.MyApplication: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4476)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:536)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:286)
            at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
            at org.codechimp.apprater.AppRater.showRateAlertDialog(AppRater.java:299)
            at org.codechimp.apprater.AppRater.app_launched(AppRater.java:175)
            at org.codechimp.apprater.AppRater.app_launched(AppRater.java:104)
            at com.soccertimer.android.utils.MyApplication.onCreate(MyApplication.java:19)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at dalvik.system.NativeStart.main(Native Method)
````

**Comment by andrew-codechimp** [comment]
You need to make the calls to AppRater within your Main Activity, not the Application class.
